---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible_role_antigen_debian_max
    image: debian:11

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: debian_max

verifier:
  name: testinfra
  directory: ../default/tests/
