---
dependency:
  name: galaxy

driver:
  name: docker

lint: |
  set -e
  yamllint .
  ansible-lint
  flake8

platforms:
  - name: ansible_role_antigen_ubuntu_max
    image: ubuntu:20.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: ubuntu_max

verifier:
  name: testinfra
  directory: ../default/tests/
